cadastros/urls.py
from django.urls import path
from .views import TaskCreate, CategoryCreate, AuditableCreate, CommentCreate, TaskUpdate, AuditableUpdate, CategoryUpdate, CommentUpdate, TaskDelete, CategoryDelete, AuditableDelete, CommentDelete, TasksList, CategoryList, AuditableList, CommentList
urlpatterns = [
    path('cadastrar/tarefa/', TaskCreate.as_view(), name='cadastro-tarefa'),
    path('cadastrar/categoria/', CategoryCreate.as_view(), name='cadastro-categoria'),
    path('cadastrar/auditoria/', AuditableCreate.as_view(), name='cadastro-auditoria'),
    path('cadastrar/comentario/', CommentCreate.as_view(), name='cadastro-comentario'),

    path('editar/tarefa/<str:pk>', TaskUpdate.as_view(), name='atualizar-tarefa'),
    path('editar/categoria/<str:pk>', CategoryUpdate.as_view(), name='atualizar-categoria'),
    path('editar/auditoria/<str:pk>', AuditableUpdate.as_view(), name='atualizar-auditoria'),
    path('editar/comentario/<str:pk>', CommentUpdate.as_view(), name='atualizar-comentario'),

    path('excluir/tarefa/<str:pk>', TaskDelete.as_view(), name='deletar-tarefa'),
    path('excluir/categoria/<str:pk>', CategoryDelete.as_view(), name='deletar-categoria'),
    path('excluir/auditoria/<str:pk>', AuditableDelete.as_view(), name='deletar-auditoria'),
    path('excluir/comentario/<str:pk>', CommentDelete.as_view(), name='deletar-comentario'),

    path('listar/tarefas/', TasksList.as_view(), name='tarefas'),
    path('listar/categorias/', CategoryList.as_view(), name='categorias'),
    path('listar/auditorias/', AuditableList.as_view(), name='auditorias'),
    path('listar/comentarios/', CommentList.as_view(), name='comentarios'),
]

paginas/urls.py
from django.urls import path
from .views import IndexView, SobreView, UmlView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('sobre/', SobreView.as_view(), name='sobre'),
    path('uml/', UmlView.as_view(), name='uml'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),                                                                             
    path('', include('usuarios.urls')), 
    path('__debug__/', include('debug_toolbar.urls')),                                                                               
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cadastros/models.py
from os import name
import uuid
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50, unique=True, verbose_name="Nome")

    def __str__(self) -> str:
        return "{}".format(self.name)
    
class Comment(models.Model):
    # TODO incluir chaves estrangeiras
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    text = models.TextField(verbose_name="Comentários")
    creation_date = models.DateField(verbose_name="Criação")    

    def __str__(self) -> str:
        return "{}".format(self.text)
    
class Auditable(models.Model):
    # mudar para histórico
    # data e hora
    # TODO incluir chaves estrangeiras
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    action = models.TextField(verbose_name="Ação")
    timestamp = models.DateField(verbose_name="Data") 

    def __str__(self) -> str:
        return "{}".format(self.action)
    
class Task(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=50, unique=True, verbose_name="Título")
    description = models.TextField(verbose_name="Descrição")
    due_date = models.DateField(verbose_name="Prazo")
    creation_date = models.DateField(verbose_name="Criação")
    completion_date = models.DateField(null=True, blank=True, verbose_name="Finalização")
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.PROTECT)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    comment = models.ForeignKey(Comment, null=True, blank=True, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='pdf/', null=True)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT, related_name="tasks_as_usuario") 


    def __str__(self) -> str:
        return "{}".format(self.title)

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):
    nome_completo = models.CharField(max_length=50, null=True)
    cpf = models.CharField(max_length=14, null=True, verbose_name='CPF')
    telefone = models.CharField(max_length=16, null=True)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

cadastros/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from .models import Task, Comment, Category, Auditable
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin

from django_filters.views import FilterView
from .filters import TaskFilter, CommentFilter
# Create your views here.

############# CADASTROS #############
class CategoryCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('signin')
    model = Category
    fields = ['name']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('categorias')

class CommentCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('signin')
    model = Comment
    fields = ['creation_date', 'text']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('comentarios')

class AuditableCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('signin')
    model = Auditable
    fields = ['timestamp', 'action']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('auditorias')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = "Cadastro de Auditorias"
        context['botao'] = "Salvar"
        return context

class TaskCreate(GroupRequiredMixin, LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('signin')
    group_required = ['admin', 'users']
    model = Task
    fields = ['title', 'description', 'due_date', 'creation_date', 'user', 'category', 'comment', 'arquivo']
    template_name = 'cadastros/form-upload.html'
    success_url = reverse_lazy('tarefas')
    
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        # não salvou no banco ainda
        url = super().form_valid(form)
        # já está salvo no banco
        return url

############# ATUALIZAÇÂO #############
class CategoryUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('signin')
    model = Category
    fields = ['name']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('categorias')

class CommentUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('signin')
    model = Comment
    fields = ['text']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('comentarios')

class AuditableUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('signin')
    model = Auditable
    fields = ['action']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('auditorias')

class TaskUpdate(GroupRequiredMixin, LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('signin')
    group_required = ['admin', 'users']
    model = Task
    fields = ['title', 'description', 'due_date', 'creation_date', 'completion_date', 'user', 'category', 'comment', 'arquivo']
    template_name = 'cadastros/form-upload.html'
    success_url = reverse_lazy('tarefas')

############# DELETE #############
class CategoryDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('signin')
    model = Category
    template_name = 'cadastros/form-delete.html'
    success_url = reverse_lazy('categorias')

class CommentDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('signin')
    model = Comment
    template_name = 'cadastros/form-delete.html'
    success_url = reverse_lazy('comentarios')

class AuditableDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('signin')
    model = Auditable
    template_name = 'cadastros/form-delete.html'
    success_url = reverse_lazy('auditorias')

class TaskDelete(GroupRequiredMixin, LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('signin')
    group_required = ['admin', 'users']
    model = Task
    template_name = 'cadastros/form-delete.html'
    success_url = reverse_lazy('tarefas') 

############# LISTA #############
class CategoryList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('signin')
    model = Category
    template_name = 'cadastros/lista/categorias.html'

class CommentList(LoginRequiredMixin, FilterView):
    login_url = reverse_lazy('signin')
    model = Comment
    template_name = 'cadastros/lista/comentarios.html'
    paginate_by = 50
    filterset_class = CommentFilter

class AuditableList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('signin')
    model = Auditable
    template_name = 'cadastros/lista/auditorias.html'

class TasksList(GroupRequiredMixin, LoginRequiredMixin, FilterView):
    login_url = reverse_lazy('signin')
    group_required = ['admin', 'users']
    model = Task
    template_name = 'cadastros/lista/tarefas.html'
    paginate_by = 50
    filterset_class = TaskFilter

    def get_queryset(self):
        self.object_list = Task.objects.filter(usuario=self.request.user)
        return self.object_list.select_related('user', 'category', 'comment') 

cadastros/templates/cadastros/filter.html
{% load static %}
{% load crispy_forms_tags %}

<style>
    form.row div[id*="div_id"] {
        flex: 0 0 auto;
        width: auto;
    }    
</style>

<form class="row justify-content-end" method="get">
    {{ filter.form|crispy }}

    <div class="col-auto">
        <label for="" class="form-label d-block">&nbsp;</label>
        <button type="submit" class="btn btn-outline-primary btn-sm">Filtrar</button>
    </div>
</form>

cadastros/templates/cadastros/form-delete.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
<title>Excluir Registros</title>
{% endblock %}

{% block content %}
<p class="lead">Confirme para excluir.</p>

<form action="" method="post">
    <p>Deseja excluir o registro: <strong>{{ object }}</strong>?</p>

    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit" class="btn btn-danger">Excluir</button>

</form>

{% endblock %} 

cadastros/templates/cadastros/form-upload.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block titulo %}
<title>{{ titulo }}</title>
{% endblock %}

{% block content %}

<h3>{{titulo|default:"Cadastros"}}</h3>
<p class="lead">Preencha todos os campos obrigatórios.</p>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Salvar</button>

</form>

{% endblock %} 

cadastros/templates/cadastros/form.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block titulo %}
<title>{{ titulo }}</title>
{% endblock %}

{% block content %}

<h3>{{titulo|default:"Cadastros"}}</h3>
<p class="lead">Preencha todos os campos obrigatórios.</p>

<form action="" method="post">
    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Salvar</button>

</form>

{% endblock %} 

{% block scripts %}
   <script src="{% static 'js/jquery.mask.min.js' %}"></script>
   <script>
    $(document).ready(function() {
        $('#id_cpf').mask('000.000.000-00');
        // $('#id_telefone').mask('(00) 00000-0000');
        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
            },
            spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
                }
            };

            $('#id_telefone').mask(SPMaskBehavior, spOptions);
        });
   </script>
{% endblock %}